version: '3'

networks:
    pre-order-backend:
        driver: bridge

services:
    pre-order-app:
        build:
            context: ./docker/development
            dockerfile: nginx.dockerfile
        ports:
            - "8090:80"
        container_name: pre-order-app
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - pre-order-php
            - pre-order-redis
            - pre-order-mysql
        networks:
            - pre-order-backend

    pre-order-mysql:
        image: mysql:8.0
        restart: unless-stopped
        container_name: pre-order-mysql
        tty: true
        volumes:
            - ./docker/development/backup:/var/lib/mysql
            - ./docker/development/data:/docker-entrypoint-initdb.d
        ports:
            - "3390:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - pre-order-backend

    pre-order-php:
        image: pre-order-php
        build:
            context: ./docker/development
            dockerfile: php.dockerfile
        container_name: pre-order-php
        ports:
            - "9090:9000"
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - pre-order-backend

    pre-order-redis:
        image: redis:alpine
        restart: unless-stopped
        container_name: pre-order-redis
        ports:
            - "6390:6379"
        networks:
            - pre-order-backend

    pre-order-queue:
        image: pre-order-php
        container_name: pre-order-queue
        restart: always
        working_dir: /var/www/html
        command: php artisan queue:work
        depends_on:
            - pre-order-php
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - pre-order-backend
